[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "chromium",
  "chromium-driver",
  "glib",
  "nss",
  "nspr",
  "atk",
  "dbus",
  "libxkbcommon",
  "libxkbcommon.dev",
  "libXcomposite",
  "libXdamage",
  "libXfixes",
  "libXrandr",
  "libgbm",
  "libdrm",
  "libxcb",
  "libxshmfence",
  "libX11",
  "libXext",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "alsa-lib",
  "at-spi2-atk",
  "gtk3"
]

[phases.install]
cmds = [
  "python3.11 -m pip install -r requirements.txt"
]

[start]
cmd = "python3.11 main.py"